suchwow/routes/auth.py
from uuid import uuid4

import requests
from flask import session, redirect, url_for, request, Blueprint

from suchwow import config


bp = Blueprint("auth", "auth")

@bp.route("/login")
def login():
    state = uuid4().hex
    session["auth_state"] = state
    url = f"{config.OIDC_URL}/auth?" \
          f"client_id={config.OIDC_CLIENT_ID}&" \
          f"redirect_uri={config.OIDC_REDIRECT_URL}&" \
          f"response_type=code&" \
          f"state={state}"

    return redirect(url)

@bp.route("/logout")
def logout():
    session["auth"] = None
    return redirect(url_for("main.index"))

@bp.route("/auth/")
def auth():
    # todo - clean up assertions
    assert "state" in request.args
    assert "session_state" in request.args
    assert "code" in request.args

    # verify state
    if not session.get("auth_state"):
        return "session error", 500
    if request.args["state"] != session["auth_state"]:
        return "attack detected :)", 500

    # with this authorization code we can fetch an access token
    url = f"{config.OIDC_URL}/token"
    data = {
        "grant_type": "authorization_code",
        "code": request.args["code"],
        "redirect_uri": config.OIDC_REDIRECT_URL,
        "client_id": config.OIDC_CLIENT_ID,
        "client_secret": config.OIDC_CLIENT_SECRET,
        "state": request.args["state"]
    }
    resp = requests.post(url, data=data)
    resp.raise_for_status()

    data = resp.json()
    assert "access_token" in data
    assert data.get("token_type") == "bearer"
    access_token = data["access_token"]

    # fetch user information with the access token
    url = f"{config.OIDC_URL}/userinfo"

    try:
        resp = requests.post(url, headers={"Authorization": f"Bearer {access_token}"})
        resp.raise_for_status()
        user_profile = resp.json()
    except:
        return resp.content, 500

    # user can now visit /secret
    session["auth"] = user_profile
    return redirect(url_for("main.index"))

suchwow/routes/leaderboard.py
from flask import render_template, Blueprint, request

from suchwow.utils.helpers import get_top_posters, get_top_posts


bp = Blueprint("leaderboard", "leaderboard")

@bp.route("/leaderboards/top_posters")
def top_posters():
    top_posters = get_top_posters()
    return render_template("leaderboard.html", posters=top_posters)

@bp.route("/leaderboards/top_posts")
def top_posts():
    days = request.args.get('days', 1)
    try:
        days = int(days)
    except:
        days = 1

    if days not in [1, 3, 7, 30, 9999]:
        days = 7

    posts = get_top_posts(days)
    return render_template("post/top.html", posts=posts, days=days)

suchwow/routes/main.py
from math import ceil

from flask import Blueprint, request, render_template, flash

from suchwow.models import Post, Profile, Moderator
from suchwow.utils.helpers import get_latest_tipped_posts

bp = Blueprint('main', 'main')


@bp.route("/")
def index():
    itp = 15
    page = request.args.get("page", 1)
    submitter = request.args.get("submitter", None)
    content = request.args.get("content", None)

    if content == 'latest_tipped':
        posts = get_latest_tipped_posts()
        return render_template(
            "index.html",
            posts=posts[0:30],
            title="Latest Tipped Memes"
        )

    try:
        page = int(page)
    except:
        flash("Wow, wtf hackerman. Cool it.", "is-danger")
        page = 1

    posts = Post.select().where(Post.approved==True).order_by(Post.timestamp.desc())
    if submitter:
        posts = posts.where(Post.submitter==submitter)

    paginated_posts = posts.paginate(page, itp)
    total_pages = ceil(posts.count() / itp)
    return render_template(
        "index.html",
        posts=paginated_posts,
        page=page,
        total_pages=total_pages,
        title="Latest Memes"
    )


@bp.route("/about")
def about():
    mods = Profile.select().join(Moderator, on=(Profile.username == Moderator.username))
    return render_template("about.html", mods=mods)

suchwow/routes/post.py
from os import path, remove
from io import BytesIO
from base64 import b64encode
from secrets import token_urlsafe

from qrcode import make as qrcode_make
from flask import render_template, Blueprint, request, flash
from flask import send_from_directory, redirect, url_for, current_app
from werkzeug.utils import secure_filename

from suchwow import wownero
from suchwow.models import Post, Profile, Comment, Ban
from suchwow.utils.decorators import login_required, profile_required, moderator_required
from suchwow.utils.helpers import allowed_file, is_moderator, get_session_user
from suchwow.utils.helpers import audit_event
from suchwow.discord import post_discord_webhook


bp = Blueprint("post", "post")

@bp.route("/post/<id>")
def read(id):
    _address_qr = BytesIO()
    qr_code = None
    if Post.filter(id=id):
        wallet = wownero.Wallet()
        post = Post.get(id=id)
        if not post.approved:
            if not is_moderator(get_session_user()):
                flash("That post has not been approved.", "is-warning")
                return redirect("/")
        if wallet.connected:
            address = wallet.get_address(account=post.account_index)
            transfers = wallet.transfers(account=post.account_index)
            qr_uri = f'wownero:{address}?tx_description=suchwow%20post%20{post.id}'
            address_qr = qrcode_make(qr_uri).save(_address_qr)
            qr_code = b64encode(_address_qr.getvalue()).decode()
        else:
            address = "?"
            transfers = "?"
        return render_template(
            "post/read.html",
            post=post,
            address=address,
            transfers=transfers,
            qr_code=qr_code
        )
    else:
        flash("No meme there, brah", "is-warning")
        return redirect(url_for("main.index"))

@bp.route("/post/create", methods=["GET", "POST"])
@login_required
@profile_required
def create():
    submitter = get_session_user()
    u = Profile.filter(username=submitter)
    banned = Ban.filter(user=u).first()
    if banned:
        flash(f"You can't post: {banned.reason}", "is-danger")
        return redirect("/")
    if request.method == "POST":
        post_title = request.form.get("title")
        # check if the post request has the file part
        if "file" not in request.files:
            flash("You didn't upload a caliente meme, bro! You're fuckin up!", "is-danger")
            return redirect(request.url)
        file = request.files["file"]
        # if user does not select file, browser also
        # submit an empty part without filename
        if file.filename == "":
            flash("You didn't upload a caliente meme, bro! You're fuckin up!", "is-danger")
            return redirect(request.url)
        if post_title == "":
            flash("You didn't give your meme a spicy title, bro! You're fuckin up!", "is-danger")
            return redirect(request.url)
        if file and allowed_file(file.filename):
            filename =  "{}-{}".format(
                token_urlsafe(12),
                secure_filename(file.filename)
            )
            save_path_base = path.join(current_app.config["DATA_FOLDER"], "uploads")
            save_path = path.join(save_path_base, filename)
            file.save(save_path)
            try:
                wallet = wownero.Wallet()
                account_index = wallet.new_account()
                in_use = Post.select().where(Post.account_index == account_index).first()
                if in_use:
                    flash("Suchwow wallet is fucked up! Try again later.", "is-danger")
                    return redirect(request.url)
            except:
                flash("Suchwow wallet is fucked up! Try again later.", "is-danger")
                return redirect(request.url)
            post = Post(
                title=post_title,
                text=request.form.get("text", ""),
                submitter=submitter,
                image_name=filename,
                account_index=account_index,
                address_index=0
            )
            post.save()
            post.save_thumbnail()
            url = url_for('post.read', id=post.id, _external=True)
            audit_event(f'Created new post {post.id}')
            flash("New post created and pending approval!", "is-success")
            return redirect(url_for("main.index"))
    return render_template("post/create.html")

@bp.route("/post/<id>/approve")
@moderator_required
def approve(id):
    post = Post.get(id=id)
    url = url_for('post.read', id=post.id, _external=True)
    if post:
        if not post.approved:
            post.approved = True
            post.save()
            flash("Approved", "is-success")
            audit_event(f'Approved post {post.id}')
        if current_app.config["DEBUG"] is False:
            post_discord_webhook(post)
        return redirect(url_for("mod.pending_posts"))
    else:
        flash("You can't approve this", "is-success")
        return redirect(url_for("main.index"))

@bp.route("/post/<id>/delete")
@login_required
def delete(id):
    filtered = Post.filter(id=id)
    user = get_session_user()
    is_mod = is_moderator(user)
    if filtered:
        post = filtered.first()
        if user == post.submitter or is_mod:
            save_path_base = path.join(current_app.config["DATA_FOLDER"], "uploads")
            save_path = path.join(save_path_base, post.image_name)
            try:
                remove(save_path)
            except:
                pass
            audit_event(f'Deleted post {post.id}')
            post.delete_instance()
            flash("Deleted that shit, brah!", "is-success")
            if is_mod:
                return redirect(url_for("mod.pending_posts"))
            else:
                return redirect(url_for("main.index"))
        else:
            flash("You can't delete a meme you don't own, brah", "is-warning")
            return redirect(url_for("post.read", id=post.id))
    else:
        flash("No meme there, brah", "is-warning")
        return redirect(url_for("main.index"))

@bp.route("/uploads/<path:filename>")
def uploaded_file(filename):
    file_path = path.join(current_app.config["DATA_FOLDER"], "uploads")
    return send_from_directory(file_path, filename)

suchwow/routes/profile.py
from flask import render_template, Blueprint, flash
from flask import request, redirect, url_for, session
from suchwow.models import Profile
from suchwow.utils.decorators import login_required


bp = Blueprint("profile", "profile")

@bp.route("/profile/edit", methods=["GET", "POST"])
@login_required
def edit():
    un = session["auth"]["preferred_username"]
    profile_exists = Profile.filter(username=un)
    if request.method == "POST":
        address = request.form.get("address")
        if len(address) in [97, 108]:
            if profile_exists:
                profile = Profile.get(username=un)
                profile.address = address
                profile.save()
            else:
                profile = Profile(
                    username=un,
                    address=address
                )
                profile.save()
            return redirect(request.args.get("redirect", "/"))
        else:
            flash("WTF bro, that's not a valid Wownero address", "is-warning")
            return redirect(request.url)
    if profile_exists:
        profile = Profile.get(username=un)
    else:
        profile = None
    return render_template("profile/edit.html", profile=profile)

suchwow/templates/about.html
{% extends 'base.html' %}

{% block content %}

<div class="container" style="text-align:center;">
  <div class="about content">
    <h1>About</h1>
    <p>Post memes! Have fun! Comment and talk shit! Earn WOW!</p>
    <p>Quit your day job and become a full-time shitposter and memer!</p>
    <p>Commiserate with the gang in IRC, get high, and let your responsibilities fall to the wayside.</p>
    <p>Join the revolution!</p>
    <br />
    <br />
    <p>If you've made WOW from memes, please consider donating to our mod team - we work hard to ensure only the finest quality memes are shown for your viewing pleasure:</p>
    {% for mod in mods %}
    <p><strong>{{ mod.username }}</strong> - {{ mod.address or '? (update your profile, bub!)' }}</p>
    {% endfor %}
    <br />
    <br />
    <br />
  </div>
</div>

{% endblock %}

suchwow/templates/base.html
<!DOCTYPE html>
 <html lang="en">
 <!--
 ░░░░░░░█▐▓▓░████▄▄▄█▀▄▓▓▓▌█ very website
 ░░░░░▄█▌▀▄▓▓▄▄▄▄▀▀▀▄▓▓▓▓▓▌█
 ░░░▄█▀▀▄▓█▓▓▓▓▓▓▓▓▓▓▓▓▀░▓▌█
 ░░█▀▄▓▓▓███▓▓▓███▓▓▓▄░░▄▓▐█▌ such html
 ░█▌▓▓▓▀▀▓▓▓▓███▓▓▓▓▓▓▓▄▀▓▓▐█
 ▐█▐██▐░▄▓▓▓▓▓▀▄░▀▓▓▓▓▓▓▓▓▓▌█▌   WOW
 █▌███▓▓▓▓▓▓▓▓▐░░▄▓▓███▓▓▓▄▀▐█
 █▐█▓▀░░▀▓▓▓▓▓▓▓▓▓██████▓▓▓▓▐█
 ▌▓▄▌▀░▀░▐▀█▄▓▓██████████▓▓▓▌█▌
 ▌▓▓▓▄▄▀▀▓▓▓▀▓▓▓▓▓▓▓▓█▓█▓█▓▓▌█▌ many memes
 █▐▓▓▓▓▓▓▄▄▄▓▓▓▓▓▓█▓█▓█▓█▓▓▓▐█
 -->
 <head>
     <meta charset="UTF-8">
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
     <meta name="viewport" content="width=device-width, initial-scale=1">

     <meta name="HandheldFriendly" content="True">
     <meta name="MobileOptimized" content="320">
     <link rel="shortcut icon" href="/static/wownero_logo.ico" type="image/x-icon" />
     {% if post %}
     <meta property="og:url" content="{{ url_for('post.read', id=post.id, _external=True) }}" />
     <meta property="og:image" content="{{ url_for('post.uploaded_file', filename=post.image_name, _external=True) }}" />
     <meta property="og:description" content="{{ post.text }}" />
     <meta property="og:title" content="SuchWow #{{ post.id }} - {{ post.title }}" />
     <meta name="twitter:title" content="SuchWow #{{ post.id }} - {{ post.title }}" />
     <meta name="twitter:description" content="{{ post.text }}" />
     <meta name="twitter:image" content="{{ url_for('post.uploaded_file', filename=post.image_name, _external=True) }}" />
     <meta name="twitter:card" content="summary_large_image" />
     {% else %}
     <meta property="og:url" content="https://suchwow.xyz/" />
     <meta property="og:image" content="https://funding.wownero.com/static/wowdoge-a.jpg" />
     <meta property="og:description" content="SuchWow! Memes n shit!" />
     <meta property="og:title" content="SuchWow!" />
     <meta name="twitter:title" content="SuchWow!" />
     <meta name="twitter:description" content="SuchWow! Memes n shit!" />
     <meta name="twitter:image" content="https://funding.wownero.com/static/wowdoge-a.jpg" />
     <meta name="twitter:card" content="summary_large_image" />
     {% endif %}
     <meta name="viewport" content="width=device-width, initial-scale=1"/>
     <meta name="theme-color" content="#ffffff">
     <meta name="apple-mobile-web-app-title" content="SuchWow!">
     <meta name="application-name" content="SuchWow!">
     <meta name="msapplication-TileColor" content="#da532c">
     <meta name="keywords" content="wownero, wow, memes, monero, xmr, cryptocurrency">
     <link href="/static/css/bulma.min.css" rel="stylesheet">
     <link href="/static/css/custom.css" rel="stylesheet">
     <title>SuchWow!</title>
 </head>

 <body>

{% include 'navbar.html' %}

{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
    <div class="notification {{ category | default('is-danger') }} container is-light">
      {{ message }}
    </div>
    {% endfor %}
  {% endif %}
{% endwith %}



 <!-- Page Content -->
 {% block content %} {% endblock %}

 <div style="padding-bottom:10em;"></div>

 <!-- Footer -->
 {% block footer %}
 <footer class="footer">
  <div class="content has-text-centered">
    <p><strong>SuchWow</strong> by <a href="https://lzahq.tech" target="_blank">lza_menace</a></p>
    <p><a href="https://wownero.org/" target="_blank">Learn more about the infamous shitcoin, Wownero</a>.</p>
  </div>
</footer>
{% endblock %}

<!-- JS -->
<script>
document.addEventListener('DOMContentLoaded', () => {

  // Get all "navbar-burger" elements
  const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

  // Check if there are any navbar burgers
  if ($navbarBurgers.length > 0) {

    // Add a click event on each of them
    $navbarBurgers.forEach( el => {
      el.addEventListener('click', () => {

        // Get the target from the "data-target" attribute
        const target = el.dataset.target;
        const $target = document.getElementById(target);

        // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
        el.classList.toggle('is-active');
        $target.classList.toggle('is-active');

      });
    });
  }

});
</script>

 </body>
 </html>

suchwow/templates/index.html
{% extends 'base.html' %}

{% block content %}

<div class="container" style="text-align:center;">

  <h1 class="title">{% if title %}{{ title }}{% else %}Latest Memes{% endif %}</h1>

  {% if request.args.content == 'latest_tipped' %}
    <a href="/">View Latest Memes</a>
  {% else %}
    <a href="/?content=latest_tipped">View Latest Tipped Posts</a>
  {% endif %}

  <section class="section">
  {% if posts %}
      {% for row in posts | batch(4) %}
        <div class="columns">
          {% for p in row %}
          {% set post = p.show() %}
          <div class="column">
            <div class="card">
              <div class="card-image">
                  <a href="{{ url_for('post.read', id=post.id) }}">
                    {% if p.get_image_path().endswith('mp4') %}
                      <video style="max-height: 100vh!important;" controls>
                        <source src="{{ url_for('post.uploaded_file', filename=p.image_name) }}" type="video/mp4">
                        Your browser does not support the video tag.
                      </video>
                    {% else %}
                      <img alt="SuchWow #{{ post.id }} - {{ post.title }} by {{ post.submitter }}" src="{{ url_for('post.uploaded_file', filename=post.thumbnail_name) }}" />
                    {% endif %}
                  </a>
              </div>
              <div class="card-content">
                <div class="media">
                  <div class="media-content">
                    <p class="title is-4">
                      <a href="{{ url_for('post.read', id=post.id) }}">{{ post.title }}</a>
                    </p>
                    <p class="subtitle is-6"><a href="/?submitter={{ post.submitter }}">{{ post.submitter }}</a></p>
                  </div>
                </div>

                <div class="content">
                  {{ post.text | truncate(60) }}
                  <p><strong>{{ post.received_wow }} WOW received</strong></p>
                  <time datetime="2016-1-1">{{ post.timestamp.year }}-{{ post.timestamp.month }}-{{ post.timestamp.day }} {{ post.timestamp.hour }}:{{ post.timestamp.minute }} UTC</time>
                  <p>({{ post.timestamp | humanize }})</p>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      {% endfor %}
  {% else %}
    <p>No posts yet!</p>
  {% endif %}
  </section>

  {% if total_pages %}
  <nav class="pagination is-centered pb-4" role="navigation" aria-label="pagination">
    <ul class="pagination-list">
      {% for p in range(1, total_pages + 1) %}
        <a href="{% if request.args.submitter %}/?submitter={{ request.args.submitter }}&{% else %}/?{% endif %}page={{ p }}" class="pagination-link {% if p == page %}current-page-btn{% endif %}">{{ p }}</a>
      {% endfor %}
    </ul>
  </nav>
  {% endif %}


</div>

{% endblock %}

suchwow/templates/leaderboard.html
{% extends 'base.html' %}

{% block content %}

<div class="container content" style="text-align:center;">

    <h1>Top Posters</h1>

  {% if posters %}
    <table class="table table-striped">
      <tr>
        <th>Submitter</th>
        <th>Post Count</th>
        <th>Amount</th>
      </tr>
      {% for poster, data in posters.items() | sort(attribute='1.amount', reverse=True) %}
        <tr>
          <td><a href="/?submitter={{ poster }}">{{ poster }}</a></td>
          <td>{{ data["posts"] | length }}</td>
          <td>{{ data["amount"] }} WOW</td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>No posts yet!</p>
  {% endif %}

  <hr>
  <a href="{{ url_for('main.index') }}"><button class="btn btn-warning">Go Home</button></a>

</div>

{% endblock %}

suchwow/templates/navbar.html
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="/">
      <img src="/static/wow_logo.png">
    </a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item" href="{{ url_for('main.index') }}">Home</a>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">Leaderboards</a>

        <div class="navbar-dropdown">
          <a class="navbar-item" href="{{ url_for('leaderboard.top_posters') }}">Top Posters</a>
          <a class="navbar-item" href="{{ url_for('leaderboard.top_posts') }}?days=1">Top Memes Last 1 Day</a>
          <a class="navbar-item" href="{{ url_for('leaderboard.top_posts') }}?days=3">Top Memes Last 3 Days</a>
          <a class="navbar-item" href="{{ url_for('leaderboard.top_posts') }}?days=7">Top Memes Last Week</a>
          <a class="navbar-item" href="{{ url_for('leaderboard.top_posts') }}?days=30">Top Memes Last Month</a>
          <a class="navbar-item" href="{{ url_for('leaderboard.top_posts') }}?days=9999">Top Memes All Time</a>
        </div>
      </div>
      <a class="navbar-item" href="{{ url_for('main.about') }}">About</a>
      <a class="navbar-item" href="{{ url_for('post.create') }}">Submit</a>
      {% if 'auth' in session %}
        {% if session.auth.preferred_username | is_moderator %}
          <a class="navbar-item" style="color: orange;" href="{{ url_for('mod.main') }}">Mods!</a>
        {% endif %}
      {% endif %}
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          {% if not 'auth' in session %}
            <a class="button is-primary" href="https://login.wownero.com/developer/"><strong>Sign up</strong></a>
            <a class="button is-light" href="{{ url_for('auth.login') }}">Log in</a>
          {% else %}
            <a class="button is-primary" href="{{ url_for('profile.edit') }}">Profile ({{ session.auth.preferred_username }})</a>
            <a class="button is-light" href="{{ url_for('auth.logout') }}">Logout</a>
          {% endif  %}
        </div>
      </div>
    </div>
  </div>
</nav>

<!-- Navigation -->
<!-- <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="/">
            <h3>SuchWow!</h3>
        </a>

        <div class="" id="">
            <ul class="navbar-nav ml-auto">
                {% if session.auth %}
                <li class="nav-item">

                </li>
                {% endif %}
                <li class="nav-item">

                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('post.create') }}">Submit</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
                </li>
                {% if session.auth == None %}
                  <li class="nav-item">
                      <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                  </li>
                {% else %}
                  <li class="nav-item">
                    {% if session.auth %}
                      <a class="nav-link" href="{{ url_for('profile.edit') }}">Profile ({{ session.auth.preferred_username }})</a>
                    {% endif %}
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                  </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav> -->