suchwow/routes/main.py
from math import ceil

from flask import Blueprint, request, render_template, flash

from suchwow.models import Post, Profile, Moderator
from suchwow.utils.helpers import get_latest_tipped_posts

bp = Blueprint('main', 'main')


@bp.route("/")
def index():
    itp = 15
    page = request.args.get("page", 1)
    submitter = request.args.get("submitter", None)
    content = request.args.get("content", None)

    if content == 'latest_tipped':
        posts = get_latest_tipped_posts()
        return render_template(
            "index.html",
            posts=posts[0:30],
            title="Latest Tipped Memes"
        )

    try:
        page = int(page)
    except:
        flash("Wow, wtf hackerman. Cool it.", "is-danger")
        page = 1

    posts = Post.select().where(Post.approved==True).order_by(Post.timestamp.desc())
    if submitter:
        posts = posts.where(Post.submitter==submitter)

    paginated_posts = posts.paginate(page, itp)
    total_pages = ceil(posts.count() / itp)
    return render_template(
        "index.html",
        posts=paginated_posts,
        page=page,
        total_pages=total_pages,
        title="Latest Memes"
    )


@bp.route("/about")
def about():
    mods = Profile.select().join(Moderator, on=(Profile.username == Moderator.username))
    return render_template("about.html", mods=mods)

suchwow/routes/mod.py
from flask import Blueprint, render_template, redirect, url_for, flash, request

from suchwow.models import AuditEvent, Post, Profile, Moderator, Ban, get_ban_reason
from suchwow.utils.decorators import moderator_required
from suchwow.utils.helpers import get_session_user, audit_event
from suchwow import config


bp = Blueprint("mod", "mod")

@bp.route('/mods')
@moderator_required
def main():
    live_posts = Post.select().where(Post.approved == True).count()
    pending_posts = Post.select().where(Post.approved == False).count()
    active_posters = Profile.select().join(Post, on=Post.submitter == Profile.username).distinct().count()
    mods = Moderator.select().count()
    return render_template(
        'mod/main.html',
        live_posts=live_posts,
        pending_posts=pending_posts,
        active_posters=active_posters,
        mods=mods
    )


@bp.route('/mods/pending')
@moderator_required
def pending_posts():
    posts = Post.select().where(Post.approved == False).order_by(Post.timestamp.asc())
    if not posts:
        flash('no posts pending', 'is-warning')
        return redirect(url_for('mod.main'))
    return render_template('mod/posts.html', posts=posts)


@bp.route('/mods/manage', methods=['GET', 'POST'])
@moderator_required
def manage_mods():
    to_delete = request.args.get('delete')
    if to_delete:
        m = Moderator.select().where(Moderator.username == to_delete).first()
        if not m:
            flash('No moderator exists with that name', 'is-danger')
        elif m.username == get_session_user():
            flash('Cannot remove yourself.', 'is-danger')
        elif m.username == config.SUPER_ADMIN:
            flash('Cannot delete super admin you son-of-a-bitch.', 'is-danger')
        else:
            m.delete_instance()
            audit_event(f'Deleted {to_delete} from mods')
            flash(f'Removed {to_delete} from mods!', 'is-success')
        return redirect(url_for('mod.manage_mods'))
    if request.method == 'POST':
        to_add = request.form.get('username', None)
        if to_add:
            u = Profile.select().where(Profile.username == to_add).first()
            if not u:
                flash('That user does not appear to exist (no profile setup yet)', 'is-danger')
            elif Moderator.select().where(Moderator.username == to_add).first():
                flash(f'{to_add} is already a mod, ya dingus.', 'is-warning')
            else:
                m = Moderator(username=to_add)
                m.save()
                audit_event(f'Added {to_add} to mods')
                flash(f'Added {to_add} to mods!', 'is-success')
    mods = Profile.select().join(Moderator, on=(Profile.username == Moderator.username))
    return render_template('mod/manage.html', mods=mods)


@bp.route('/mods/bans', methods=['GET', 'POST'])
@moderator_required
def manage_bans():
    to_delete = request.args.get('delete')
    if to_delete:
        ban = Ban.select().join(Profile).where(Profile.username == to_delete).first()
        if not ban:
            flash('No ban exists for that user', 'is-danger')
        elif ban.user == get_session_user():
            flash('Cannot ban yourself.', 'is-danger')
        elif ban.user == config.SUPER_ADMIN:
            flash('Cannot ban super admin you son-of-a-bitch.', 'is-danger')
        else:
            ban.delete_instance()
            audit_event(f'Removed ban on {to_delete}')
            flash(f'Unbanned {to_delete}!', 'is-success')
        return redirect(url_for('mod.manage_bans'))
    if request.method == 'POST':
        to_add = request.form.get('username', None)
        if to_add:
            u = Profile.select().where(Profile.username == to_add).first()
            if not u:
                flash('That user does not appear to exist (no profile setup yet)', 'is-danger')
            elif Ban.select().join(Profile).where(Profile.username == to_add).first():
                flash(f'{to_add} is already banned, ya dingus.', 'is-warning')
            elif to_add == config.SUPER_ADMIN:
                flash('Cannot ban the super admin you son-of-a-bitch.', 'is-danger')
            else:
                reason = request.form.get('reason')
                if not reason:
                    reason = get_ban_reason()
                ban = Ban(user=u, reason=reason)
                ban.save()
                audit_event(f'Banned {to_add} ({reason})')
                flash(f'Banned {to_add}!', 'is-success')
    bans = Ban.select()
    return render_template('mod/bans.html', bans=bans)


@bp.route('/mods/logs')
@moderator_required
def view_logs():
    events = AuditEvent.select().order_by(AuditEvent.timestamp.desc()).limit(50)
    return render_template('mod/logs.html', logs=events)

suchwow/routes/post.py
from os import path, remove
from io import BytesIO
from base64 import b64encode
from secrets import token_urlsafe

from qrcode import make as qrcode_make
from flask import render_template, Blueprint, request, flash
from flask import send_from_directory, redirect, url_for, current_app
from werkzeug.utils import secure_filename

from suchwow import wownero
from suchwow.models import Post, Profile, Comment, Ban
from suchwow.utils.decorators import login_required, profile_required, moderator_required
from suchwow.utils.helpers import allowed_file, is_moderator, get_session_user
from suchwow.utils.helpers import audit_event
from suchwow.discord import post_discord_webhook


bp = Blueprint("post", "post")

@bp.route("/post/<id>")
def read(id):
    _address_qr = BytesIO()
    qr_code = None
    if Post.filter(id=id):
        wallet = wownero.Wallet()
        post = Post.get(id=id)
        if not post.approved:
            if not is_moderator(get_session_user()):
                flash("That post has not been approved.", "is-warning")
                return redirect("/")
        if wallet.connected:
            address = wallet.get_address(account=post.account_index)
            transfers = wallet.transfers(account=post.account_index)
            qr_uri = f'wownero:{address}?tx_description=suchwow%20post%20{post.id}'
            address_qr = qrcode_make(qr_uri).save(_address_qr)
            qr_code = b64encode(_address_qr.getvalue()).decode()
        else:
            address = "?"
            transfers = "?"
        return render_template(
            "post/read.html",
            post=post,
            address=address,
            transfers=transfers,
            qr_code=qr_code
        )
    else:
        flash("No meme there, brah", "is-warning")
        return redirect(url_for("main.index"))

@bp.route("/post/create", methods=["GET", "POST"])
@login_required
@profile_required
def create():
    submitter = get_session_user()
    u = Profile.filter(username=submitter)
    banned = Ban.filter(user=u).first()
    if banned:
        flash(f"You can't post: {banned.reason}", "is-danger")
        return redirect("/")
    if request.method == "POST":
        post_title = request.form.get("title")
        # check if the post request has the file part
        if "file" not in request.files:
            flash("You didn't upload a caliente meme, bro! You're fuckin up!", "is-danger")
            return redirect(request.url)
        file = request.files["file"]
        # if user does not select file, browser also
        # submit an empty part without filename
        if file.filename == "":
            flash("You didn't upload a caliente meme, bro! You're fuckin up!", "is-danger")
            return redirect(request.url)
        if post_title == "":
            flash("You didn't give your meme a spicy title, bro! You're fuckin up!", "is-danger")
            return redirect(request.url)
        if file and allowed_file(file.filename):
            filename =  "{}-{}".format(
                token_urlsafe(12),
                secure_filename(file.filename)
            )
            save_path_base = path.join(current_app.config["DATA_FOLDER"], "uploads")
            save_path = path.join(save_path_base, filename)
            file.save(save_path)
            try:
                wallet = wownero.Wallet()
                account_index = wallet.new_account()
                in_use = Post.select().where(Post.account_index == account_index).first()
                if in_use:
                    flash("Suchwow wallet is fucked up! Try again later.", "is-danger")
                    return redirect(request.url)
            except:
                flash("Suchwow wallet is fucked up! Try again later.", "is-danger")
                return redirect(request.url)
            post = Post(
                title=post_title,
                text=request.form.get("text", ""),
                submitter=submitter,
                image_name=filename,
                account_index=account_index,
                address_index=0
            )
            post.save()
            post.save_thumbnail()
            url = url_for('post.read', id=post.id, _external=True)
            audit_event(f'Created new post {post.id}')
            flash("New post created and pending approval!", "is-success")
            return redirect(url_for("main.index"))
    return render_template("post/create.html")

@bp.route("/post/<id>/approve")
@moderator_required
def approve(id):
    post = Post.get(id=id)
    url = url_for('post.read', id=post.id, _external=True)
    if post:
        if not post.approved:
            post.approved = True
            post.save()
            flash("Approved", "is-success")
            audit_event(f'Approved post {post.id}')
        if current_app.config["DEBUG"] is False:
            post_discord_webhook(post)
        return redirect(url_for("mod.pending_posts"))
    else:
        flash("You can't approve this", "is-success")
        return redirect(url_for("main.index"))

@bp.route("/post/<id>/delete")
@login_required
def delete(id):
    filtered = Post.filter(id=id)
    user = get_session_user()
    is_mod = is_moderator(user)
    if filtered:
        post = filtered.first()
        if user == post.submitter or is_mod:
            save_path_base = path.join(current_app.config["DATA_FOLDER"], "uploads")
            save_path = path.join(save_path_base, post.image_name)
            try:
                remove(save_path)
            except:
                pass
            audit_event(f'Deleted post {post.id}')
            post.delete_instance()
            flash("Deleted that shit, brah!", "is-success")
            if is_mod:
                return redirect(url_for("mod.pending_posts"))
            else:
                return redirect(url_for("main.index"))
        else:
            flash("You can't delete a meme you don't own, brah", "is-warning")
            return redirect(url_for("post.read", id=post.id))
    else:
        flash("No meme there, brah", "is-warning")
        return redirect(url_for("main.index"))

@bp.route("/uploads/<path:filename>")
def uploaded_file(filename):
    file_path = path.join(current_app.config["DATA_FOLDER"], "uploads")
    return send_from_directory(file_path, filename)

suchwow/templates/mod/bans.html
{% extends 'base.html' %}

{% block content %}

<div class="container" style="text-align:center;">
  <h1 class="title">Manage Mods</h1>
  <section class="section">
    {% for ban in bans %}
      <article class="message" style="width: 30%; margin: 2em auto;">
        <div class="message-header">
          <p>{{ ban.user.username }}</p>
          <a href="?delete={{ ban.user.username }}" class="delete"></a>
        </div>
        <div class="message-body">
          {{ ban.reason }}
        </div>
      </article>
    {% endfor %}
  </section>
  <div class="container" style="text-align:left; width: 30%;">
    <form method="post">
      <div class="field">
        <label class="label">Ban User</label>
        <div class="control">
          <input class="input" type="text" placeholder="Username" name="username">
        </div>
      </div>
      <div class="field">
        <label class="label">Reason</label>
        <div class="control">
          <textarea class="textarea" placeholder="Reason for ban" name="reason"></textarea>
        </div>
      </div>
      <div class="field is-grouped">
        <div class="control">
          <button class="button is-link">Submit</button>
        </div>
        <div class="control">
          <button class="button is-link is-light">Cancel</button>
        </div>
      </div>
    </form>
  </div>
</div>




{% endblock %}

{% block footer %}{% endblock %}

suchwow/templates/mod/logs.html
{% extends 'base.html' %}

{% block content %}

<div class="container" style="text-align:center;">
  <h1 class="title">View Logs</h1>
  <section class="section">
    {% for log in logs %}
      <article class="message" style="width: 40%; margin: 1em auto;">
        <div class="message-header">
          <p>{{ log.user.username }} - {{ log.timestamp | humanize }} </p>
        </div>
        <div class="message-body">
          {{ log.action }}
        </div>
      </article>
    {% endfor %}
  </section>
</div>

{% endblock %}

{% block footer %}{% endblock %}

suchwow/templates/mod/main.html
{% extends 'base.html' %}

{% block content %}

<div class="container content" style="padding-top: 4em;">
    
    
    <nav class="level">
      <div class="level-item has-text-centered">
        <div>
          <p class="heading">Live Memes</p>
          <p class="title">{{ live_posts }}</p>
        </div>
      </div>
      <div class="level-item has-text-centered">
        <div>
          <p class="heading">Pending Memes</p>
          <p class="title">{{ pending_posts }}</p>
        </div>
      </div>
      <div class="level-item has-text-centered">
        <div>
          <p class="heading">Active Posters</p>
          <p class="title">{{ active_posters }}</p>
        </div>
      </div>
      <div class="level-item has-text-centered">
        <div>
          <p class="heading">Mods</p>
          <p class="title">{{ mods }}</p>
        </div>
      </div>
    </nav>
    <div class="tabs is-toggle is-fullwidth">
      <ul>
        <li>
          <a href="{{ url_for('mod.pending_posts') }}">
            <span class="icon is-small"></span>
            <span>Manage Queue</span>
          </a>
        </li>
        <li>
          <a href="{{ url_for('mod.manage_bans') }}">
            <span class="icon is-small"></span>
            <span>Manage Bans</span>
          </a>
        </li>
        <li>
          <a href="{{ url_for('mod.manage_mods') }}">
            <span class="icon is-small"></span>
            <span>Manage Mods</span>
          </a>
        </li>
        <li>
          <a href="{{ url_for('mod.view_logs') }}">
            <span class="icon is-small"></span>
            <span>View Logs</span>
          </a>
        </li>
      </ul>
    </div>
    <figure>
      <img src="https://suchwow.xyz/uploads/pg1VwHJWeKT5dWXy-wowcomfysemifinal.gif">
    </figure>
    <div style="padding-bottom:10em;"></div>
</div>



{% endblock %}

{% block footer %}{% endblock %}

suchwow/templates/mod/manage.html
{% extends 'base.html' %}

{% block content %}

<div class="container" style="text-align:center;">
  <h1 class="title">Manage Mods</h1>
  <section class="section">
    {% for mod in mods %}
      <div class="block">
        <span class="tag is-large">
          {{ mod.username }}
          <a href="?delete={{ mod.username }}" class="delete"></a>
        </span>
      </div>
    {% endfor %}
  </section>
  <div class="container" style="text-align:left; width: 30%;">
    <form method="post">
      <div class="field">
        <label class="label">Add New Mod</label>
        <div class="control">
          <input class="input" type="text" placeholder="Username" name="username">
        </div>
      </div>
      <div class="field is-grouped">
        <div class="control">
          <button class="button is-link">Submit</button>
        </div>
        <div class="control">
          <button class="button is-link is-light">Cancel</button>
        </div>
      </div>
    </form>
  </div>
</div>




{% endblock %}

{% block footer %}{% endblock %}

suchwow/templates/mod/posts.html
{% extends 'base.html' %}

{% block content %}

<div class="container" style="text-align:center;">

  <h1 class="title">Pending Posts</h1>
  <section class="section">
  {% if posts %}
      {% for row in posts | batch(4) %}
        <div class="columns">
          {% for p in row %}
          {% set post = p.show() %}
          <div class="column">
            <div class="card">
              <div class="card-image">
                <a href="{{ url_for('post.read', id=p.id) }}">
                {% if p.get_image_path().endswith('mp4') %}
                  <video style="max-height: 100vh!important;" controls>
                    <source src="{{ url_for('post.uploaded_file', filename=p.image_name) }}" type="video/mp4">
                    Your browser does not support the video tag.
                  </video>
                {% else %}
                  <img alt="SuchWow #{{ post.id }} - {{ post.title }} by {{ post.submitter }}" src="{{ url_for('post.uploaded_file', filename=post.thumbnail_name) }}" />
                {% endif %}
                </a>
              </div>
              <div class="card-content">
                <div class="media">
                  <div class="media-content">
                    <p class="title is-4">
                      <a href="{{ url_for('post.read', id=p.id) }}">{{ post.title }}</a>
                    </p>
                    <p class="subtitle is-6"><a href="/?submitter={{ post.submitter }}">{{ post.submitter }}</a></p>
                  </div>
                </div>

                <div class="content">
                  {{ post.text | truncate(60) }}
                  <time datetime="2016-1-1">{{ post.timestamp.year }}-{{ post.timestamp.month }}-{{ post.timestamp.day }} {{ post.timestamp.hour }}:{{ post.timestamp.minute }} UTC</time>
                  <p>({{ post.timestamp | humanize }})</p>
                </div>
              </div>
              <footer class="card-footer">
                <a href="{{ url_for('post.approve', id=post.id) }}" class="card-footer-item" style="color:green;"><strong>Approve</strong></a>
                <a href="{{ url_for('post.delete', id=post.id) }}" class="card-footer-item" style="color:red;"><strong>Deny</strong></a>
              </footer>
            </div>
          </div>
          {% endfor %}
        </div>
      {% endfor %}
  {% else %}
    <p>No posts pending!</p>
  {% endif %}
  </section>
</div>

{% endblock %}

{% block footer %}{% endblock %}